# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 58bf7379d12a1a6fdcb6290259d2381a94e739e92c68edbc438eab62fe80d1615899d471886c0431fbce47d25776006e50e557d9507d70dbb5391c26237fcad0

test:
  secret_key_base: 9490e8c183adc63c5d8c6f8a29332aa14002f2a51a2556f7ea3dc32eedfd038e1fccda8ab929e53f7258f21116616b4514092a98cc1e83a95f1d579f80c6eaf4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
